controllers:
    resource: ../src/**/*Controller.php
    type: attribute
    defaults:
        _format: json

api_login:
    path: /api/login
    controller: lexik_jwt_authentication.controller.authentication::authenticateAction
    defaults:
        _format: json
